#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:5.0-buster-slim AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:5.0-buster-slim AS build
WORKDIR /src
COPY ["MasivianTechnicalTest.WebService/MasivianTechnicalTest.WebService.csproj", "MasivianTechnicalTest.WebService/"]
RUN dotnet restore "MasivianTechnicalTest.WebService/MasivianTechnicalTest.WebService.csproj"
COPY . .
WORKDIR "/src/MasivianTechnicalTest.WebService"
RUN dotnet build "MasivianTechnicalTest.WebService.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "MasivianTechnicalTest.WebService.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "MasivianTechnicalTest.WebService.dll"]